repos:
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v0.800
   hooks:
     - id: mypy
       files: ^(practipy/|tests/)
 - repo: local
   hooks:
     - id: black
       name: black
       entry: black
       language: system
       types: [ python ]
       files: ^(practipy/|tests/)

     - id: isort
       name: isort
       entry: isort
       language: system
       types: [ python ]
       include: ^(practipy/|tests/)
       exclude: '.*/migrations/.*'
      
     - id: flake8
       name: flake8
       entry: flake8
       language: system
       types: [ python ]
       files: ^(practipy/|tests/)

